flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpeg"
name: event_organization
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.8
  firebase_core: ^2.27.0
  onesignal_flutter: ^5.0.4


  firebase_auth: ^4.17.8   # ✅ latest stable as of now
#  firebase_auth_web: ^5.8.13
#  firebase_core_web: ^2.13.1
  cloud_firestore: ^4.15.3
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.2.1
  local_auth: ^2.1.7
  android_intent_plus: ^4.0.1
  qr_flutter: ^4.1.0
  provider: ^6.1.2
  csv: ^6.0.0
  pdf: ^3.10.8
  url_launcher: ^6.2.6
  charts_flutter: ^0.12.0
  google_maps_flutter: ^2.6.0
  mailer: ^6.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  # js: ^0.6.7 # Uncomment if JS interop is needed
  intl: any
  connectivity_plus: ^5.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/profile.jpg
    - assets/event_image.jpg
