// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP7AwksQyr-pbW6zCjLBgBkQfK1Jzhrt4',
    appId: '1:262415801583:web:cdbb25fa880369df920f1a',
    messagingSenderId: '262415801583',
    projectId: 'event-management-9cc18',
    authDomain: 'event-management-9cc18.firebaseapp.com',
    storageBucket: 'event-management-9cc18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxdPI7JIpQY9mjd2fWlU-ez4qNXY3wB2I',
    appId: '1:262415801583:android:c50c620d4b940d79920f1a',
    messagingSenderId: '262415801583',
    projectId: 'event-management-9cc18',
    storageBucket: 'event-management-9cc18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMj7gIdSpwMWrlwwKrNjZsCGn2KlP9uB8',
    appId: '1:262415801583:ios:c5dbd99256acdc3f920f1a',
    messagingSenderId: '262415801583',
    projectId: 'event-management-9cc18',
    storageBucket: 'event-management-9cc18.firebasestorage.app',
    iosBundleId: 'com.example.eventManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMj7gIdSpwMWrlwwKrNjZsCGn2KlP9uB8',
    appId: '1:262415801583:ios:c5dbd99256acdc3f920f1a',
    messagingSenderId: '262415801583',
    projectId: 'event-management-9cc18',
    storageBucket: 'event-management-9cc18.firebasestorage.app',
    iosBundleId: 'com.example.eventManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP7AwksQyr-pbW6zCjLBgBkQfK1Jzhrt4',
    appId: '1:262415801583:web:f35a2d93d1e5b337920f1a',
    messagingSenderId: '262415801583',
    projectId: 'event-management-9cc18',
    authDomain: 'event-management-9cc18.firebaseapp.com',
    storageBucket: 'event-management-9cc18.firebasestorage.app',
  );
}
